Tutorial.rst: Explaination of .coafile
coala/documentation pull request #474
Opened 2017-10-29 08:18 UTC by Kanav-7

This explains working of .coafile in getting started document

Closes https://github.com/coala/coala/issues/4787

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

2017-10-29 10:06 UTC, acashmkj approved these changes
LGTM

2017-11-02 00:34 UTC, jayvdb requested changes

2017-11-02 00:34 UTC, jayvdb commented on Users/Tutorial.rst
> +    - The ``bears key`` specifies which bears (plugins) you want to use.
"``bears key``" is not a thing.  It is "``bears`` key"

2017-11-02 17:43 UTC, Kanav-7 commented
@jayvdb Made required changes. Please review.

2017-11-05 03:06 UTC, PlentyMore commented
please squash the commits

2017-11-08 19:17 UTC, prashant0598 requested changes
@Kanav-7 commit according to commit guidelines  https://coala.io/commit and squash your commits For squashing Refer: https://api.coala.io/en/latest/Developers/Git_Basics.html

2017-11-09 19:36 UTC, IpshitaC requested changes
Hey @Kanav-7 
As explained [here](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-7-review-process), when someone requests a change on your PR, you need to amend the previous commit and not create a new one.
Can you please squash these two commits into a single commit? Refer to [this](http://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits) for more details.

2017-12-01 17:12 UTC, Kanav-7 commented
@jayvdb @IpshitaC Squashed Commits. Please review (sorry for being late)

2018-03-10 16:36 UTC, Mohit17067 approved these changes
ack a05c5f9df68351620b8a8a33a4c18b29454c4988

2018-04-08 11:45 UTC, jayvdb requested changes
The last line of the commit message should contain a URL to the issue.

2020-06-22 13:28 UTC, closed without merging